@PORT = 8080

GET http://localhost:{{PORT}}/v1/shelves

###
GET http://localhost:{{PORT}}/v1/shelves/1

###
POST http://localhost:{{PORT}}/v1/shelves
Content-Type: application/json

{
  "theme": "Fiction",
  "size": "5"
}

###
DELETE http://localhost:{{PORT}}/v1/shelves/0
